name: core
description: Modul bersama Ditonton berisi konstanta, tema, database helper, jaringan (SSL pinning), dan widget umum.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  equatable: ^2.0.7
  firebase_analytics: ^12.0.4
  firebase_core: ^4.1.4
  firebase_crashlytics: ^5.0.4
  flutter_bloc: ^9.1.1
  google_fonts: ^6.2.1
  http: ^1.2.2
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^10.0.0
  build_runner: ^2.4.14
  flutter_lints: ^6.0.0
  mockito: ^5.4.5
  sqflite_common_ffi: ^2.3.4

flutter:
  assets:
    - assets/certificates/
    - assets/images/
    - assets/fonts/
