// Mocks generated by Mockito 5.4.6 from annotations
// in tv_series/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i7;
import 'dart:convert' as _i29;
import 'dart:typed_data' as _i30;

import 'package:core/core.dart' as _i8;
import 'package:dartz/dartz.dart' as _i2;
import 'package:http/http.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:sqflite/sqflite.dart' as _i17;
import 'package:tv_series/src/data/datasources/tv_series_local_data_source.dart'
    as _i14;
import 'package:tv_series/src/data/datasources/tv_series_remote_data_source.dart'
    as _i12;
import 'package:tv_series/src/data/models/season_detail_model.dart' as _i4;
import 'package:tv_series/src/data/models/tv_series_detail_model.dart' as _i3;
import 'package:tv_series/src/data/models/tv_series_model.dart' as _i13;
import 'package:tv_series/src/data/models/tv_series_table.dart' as _i15;
import 'package:tv_series/src/domain/entities/season_detail.dart' as _i11;
import 'package:tv_series/src/domain/entities/tv_series.dart' as _i9;
import 'package:tv_series/src/domain/entities/tv_series_detail.dart' as _i10;
import 'package:tv_series/src/domain/repositories/tv_series_repository.dart'
    as _i5;
import 'package:tv_series/src/domain/usecases/get_on_the_air_tv_series.dart'
    as _i18;
import 'package:tv_series/src/domain/usecases/get_popular_tv_series.dart'
    as _i19;
import 'package:tv_series/src/domain/usecases/get_season_detail.dart' as _i24;
import 'package:tv_series/src/domain/usecases/get_top_rated_tv_series.dart'
    as _i20;
import 'package:tv_series/src/domain/usecases/get_tv_series_detail.dart'
    as _i21;
import 'package:tv_series/src/domain/usecases/get_tv_series_recommendations.dart'
    as _i22;
import 'package:tv_series/src/domain/usecases/get_tv_series_watchlist_status.dart'
    as _i26;
import 'package:tv_series/src/domain/usecases/get_watchlist_tv_series.dart'
    as _i25;
import 'package:tv_series/src/domain/usecases/remove_tv_series_watchlist.dart'
    as _i28;
import 'package:tv_series/src/domain/usecases/save_tv_series_watchlist.dart'
    as _i27;
import 'package:tv_series/src/domain/usecases/search_tv_series.dart' as _i23;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesDetailResponse_1 extends _i1.SmartFake
    implements _i3.TvSeriesDetailResponse {
  _FakeTvSeriesDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSeasonDetailResponse_2 extends _i1.SmartFake
    implements _i4.SeasonDetailResponse {
  _FakeSeasonDetailResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesRepository_3 extends _i1.SmartFake
    implements _i5.TvSeriesRepository {
  _FakeTvSeriesRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_4 extends _i1.SmartFake implements _i6.Response {
  _FakeResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_5 extends _i1.SmartFake
    implements _i6.StreamedResponse {
  _FakeStreamedResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i5.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>
  getOnTheAirTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTvSeries, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#getOnTheAirTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>
  getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#getPopularTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>
  getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#getTopRatedTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i10.TvSeriesDetail>> getTvSeriesDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, _i10.TvSeriesDetail>>.value(
                  _FakeEither_0<_i8.Failure, _i10.TvSeriesDetail>(
                    this,
                    Invocation.method(#getTvSeriesDetail, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, _i10.TvSeriesDetail>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>
  getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#getTvSeriesRecommendations, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>> searchTvSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#searchTvSeries, [query]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i11.SeasonDetail>> getSeasonDetail(
    int? id,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSeasonDetail, [id, seasonNumber]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, _i11.SeasonDetail>>.value(
                  _FakeEither_0<_i8.Failure, _i11.SeasonDetail>(
                    this,
                    Invocation.method(#getSeasonDetail, [id, seasonNumber]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, _i11.SeasonDetail>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> saveWatchlist(
    _i10.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [tvSeries]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#saveWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> removeWatchlist(
    _i10.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);

  @override
  _i7.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>
  getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#getWatchlistTvSeries, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i12.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i13.TvSeriesModel>> getOnTheAirTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getOnTheAirTvSeries, []),
            returnValue: _i7.Future<List<_i13.TvSeriesModel>>.value(
              <_i13.TvSeriesModel>[],
            ),
          )
          as _i7.Future<List<_i13.TvSeriesModel>>);

  @override
  _i7.Future<List<_i13.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue: _i7.Future<List<_i13.TvSeriesModel>>.value(
              <_i13.TvSeriesModel>[],
            ),
          )
          as _i7.Future<List<_i13.TvSeriesModel>>);

  @override
  _i7.Future<List<_i13.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue: _i7.Future<List<_i13.TvSeriesModel>>.value(
              <_i13.TvSeriesModel>[],
            ),
          )
          as _i7.Future<List<_i13.TvSeriesModel>>);

  @override
  _i7.Future<_i3.TvSeriesDetailResponse> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue: _i7.Future<_i3.TvSeriesDetailResponse>.value(
              _FakeTvSeriesDetailResponse_1(
                this,
                Invocation.method(#getTvSeriesDetail, [id]),
              ),
            ),
          )
          as _i7.Future<_i3.TvSeriesDetailResponse>);

  @override
  _i7.Future<List<_i13.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue: _i7.Future<List<_i13.TvSeriesModel>>.value(
              <_i13.TvSeriesModel>[],
            ),
          )
          as _i7.Future<List<_i13.TvSeriesModel>>);

  @override
  _i7.Future<List<_i13.TvSeriesModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue: _i7.Future<List<_i13.TvSeriesModel>>.value(
              <_i13.TvSeriesModel>[],
            ),
          )
          as _i7.Future<List<_i13.TvSeriesModel>>);

  @override
  _i7.Future<_i4.SeasonDetailResponse> getSeasonDetail(
    int? id,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSeasonDetail, [id, seasonNumber]),
            returnValue: _i7.Future<_i4.SeasonDetailResponse>.value(
              _FakeSeasonDetailResponse_2(
                this,
                Invocation.method(#getSeasonDetail, [id, seasonNumber]),
              ),
            ),
          )
          as _i7.Future<_i4.SeasonDetailResponse>);
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i14.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> insertWatchlist(_i15.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [tvSeries]),
            returnValue: _i7.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> removeWatchlist(_i15.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i7.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i15.TvSeriesTable?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i7.Future<_i15.TvSeriesTable?>.value(),
          )
          as _i7.Future<_i15.TvSeriesTable?>);

  @override
  _i7.Future<List<_i15.TvSeriesTable>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue: _i7.Future<List<_i15.TvSeriesTable>>.value(
              <_i15.TvSeriesTable>[],
            ),
          )
          as _i7.Future<List<_i15.TvSeriesTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i8.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i17.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i7.Future<_i17.Database?>.value(),
          )
          as _i7.Future<_i17.Database?>);

  @override
  _i7.Future<int> insertWatchlist(Map<String, dynamic>? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> removeWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [id]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<int> insertTvSeriesWatchlist(Map<String, dynamic>? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertTvSeriesWatchlist, [tvSeries]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<int> removeTvSeriesWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#removeTvSeriesWatchlist, [id]),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<Map<String, dynamic>?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [GetOnTheAirTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetOnTheAirTvSeries extends _i1.Mock
    implements _i18.GetOnTheAirTvSeries {
  MockGetOnTheAirTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
}

/// A class which mocks [GetPopularTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPopularTvSeries extends _i1.Mock
    implements _i19.GetPopularTvSeries {
  MockGetPopularTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
}

/// A class which mocks [GetTopRatedTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopRatedTvSeries extends _i1.Mock
    implements _i20.GetTopRatedTvSeries {
  MockGetTopRatedTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
}

/// A class which mocks [GetTvSeriesDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSeriesDetail extends _i1.Mock implements _i21.GetTvSeriesDetail {
  MockGetTvSeriesDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i10.TvSeriesDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, _i10.TvSeriesDetail>>.value(
                  _FakeEither_0<_i8.Failure, _i10.TvSeriesDetail>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, _i10.TvSeriesDetail>>);
}

/// A class which mocks [GetTvSeriesRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSeriesRecommendations extends _i1.Mock
    implements _i22.GetTvSeriesRecommendations {
  MockGetTvSeriesRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
}

/// A class which mocks [SearchTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchTvSeries extends _i1.Mock implements _i23.SearchTvSeries {
  MockSearchTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>> execute(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [query]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#execute, [query]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
}

/// A class which mocks [GetSeasonDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSeasonDetail extends _i1.Mock implements _i24.GetSeasonDetail {
  MockGetSeasonDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, _i11.SeasonDetail>> execute(
    int? id,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id, seasonNumber]),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, _i11.SeasonDetail>>.value(
                  _FakeEither_0<_i8.Failure, _i11.SeasonDetail>(
                    this,
                    Invocation.method(#execute, [id, seasonNumber]),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, _i11.SeasonDetail>>);
}

/// A class which mocks [GetWatchlistTvSeries].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchlistTvSeries extends _i1.Mock
    implements _i25.GetWatchlistTvSeries {
  MockGetWatchlistTvSeries() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue:
                _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>.value(
                  _FakeEither_0<_i8.Failure, List<_i9.TvSeries>>(
                    this,
                    Invocation.method(#execute, []),
                  ),
                ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, List<_i9.TvSeries>>>);
}

/// A class which mocks [GetTvSeriesWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTvSeriesWatchListStatus extends _i1.Mock
    implements _i26.GetTvSeriesWatchListStatus {
  MockGetTvSeriesWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i7.Future<bool> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}

/// A class which mocks [SaveTvSeriesWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveTvSeriesWatchlist extends _i1.Mock
    implements _i27.SaveTvSeriesWatchlist {
  MockSaveTvSeriesWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> execute(
    _i10.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tvSeries]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#execute, [tvSeries]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);
}

/// A class which mocks [RemoveTvSeriesWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveTvSeriesWatchlist extends _i1.Mock
    implements _i28.RemoveTvSeriesWatchlist {
  MockRemoveTvSeriesWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.TvSeriesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTvSeriesRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.TvSeriesRepository);

  @override
  _i7.Future<_i2.Either<_i8.Failure, String>> execute(
    _i10.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [tvSeries]),
            returnValue: _i7.Future<_i2.Either<_i8.Failure, String>>.value(
              _FakeEither_0<_i8.Failure, String>(
                this,
                Invocation.method(#execute, [tvSeries]),
              ),
            ),
          )
          as _i7.Future<_i2.Either<_i8.Failure, String>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i6.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i6.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i7.Future<_i6.Response>.value(
              _FakeResponse_4(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i6.Response>);

  @override
  _i7.Future<_i6.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i7.Future<_i6.Response>.value(
              _FakeResponse_4(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<_i6.Response>);

  @override
  _i7.Future<_i6.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i6.Response>.value(
              _FakeResponse_4(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i6.Response>);

  @override
  _i7.Future<_i6.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i6.Response>.value(
              _FakeResponse_4(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i6.Response>);

  @override
  _i7.Future<_i6.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i6.Response>.value(
              _FakeResponse_4(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i6.Response>);

  @override
  _i7.Future<_i6.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i29.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i7.Future<_i6.Response>.value(
              _FakeResponse_4(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i7.Future<_i6.Response>);

  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i7.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i30.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i7.Future<_i30.Uint8List>.value(_i30.Uint8List(0)),
          )
          as _i7.Future<_i30.Uint8List>);

  @override
  _i7.Future<_i6.StreamedResponse> send(_i6.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i7.Future<_i6.StreamedResponse>.value(
              _FakeStreamedResponse_5(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i7.Future<_i6.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
